databases:
  - name: library_management
    user: viny

services:
  - type: web
    name: library_management
    runtime: python
    buildCommand: "npm install && npm run build"
    startCommand: "cd backend && python -m pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py runserver"
    envVars:
      - key: SECRET_KEY
        generateValue: true
